/* TABLE USER */
CREATE TABLE users(
    pk_user BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(180) NOT NULL UNIQUE,
    name VARCHAR(90) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    phone VARCHAR(90) NOT NULL UNIQUE,
    img VARCHAR(255) NULL,
    password VARCHAR(90) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);